### ISSUE TITLE
Problem using this plugin

### ISSUE THREAD

**Issue by mberg2007** [Gustash/flutter_geolocation#1]
Hello,

In every emulator I've tried, as well as directly on my Galaxy Note 4 phone running Android 6.0.1, the following call just never returns:

```
print("Before");
coordinates = await GpsCoordinates.gpsCoordinates;`
print("After");

```
I see "before" but that's it, I never see the "after".

Do you have any ideas or suggestions as to what might be causing this?

**Comment by Gustash** [comment]
You're probably getting a PlatformException. Sorry for the late response. If you still have the project can you try and catch the gpsCoordinates call and send me the error message?

**Comment by gerryhigh** [comment]
With Flutter beta 2 it is now throwing an error " type 'Future<dynamic>' is not a subtype of type 'Future<Map<String, double>>' where..." from line 10 in gps_coordinates.dart

static Future<Map<String, double>> get gpsCoordinates =>
    _channel.invokeMethod('getGPSCoordinates');

**Comment by Gustash** [comment]
Did you make any changes to the code? I haven't tested it with new versions of Flutter.

**Comment by speroamey** [comment]
Please can you send the entire error msg. After your "where" what is written.
It's just sound like  type compatibility.
You should change the type to match the return type of the function _channel.invokeMethod('getGPSCoordinates')

**Comment by gerryhigh** [comment]
Sorry for not responding sooner. Because of the issues I switched to using this plugin (https://github.com/Lyokone/flutterlocation) so haven't revisited this issue. I can say that I made no changes to the code.

**Comment by Gustash** [comment]
I am closing this issue as there are better alternatives that are still being supported. I added a warning in the README so people know they shouldn't use this pet project. Thanks for the interest!
